services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/app
    container_name: streamer-${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
